config/routes.rb
Rails.application.routes.draw do

  root 'tutorial#inaturalist'
  match '/observations', to: 'tutorial#observations', via: 'get'
  match '/organisms', to: 'tutorial#organisms', via: 'get'
  match '/identifications', to: 'tutorial#identifications', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tutorial_controller.rb
class TutorialController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
   end
end

app/helpers/tutorial_helper.rb
module TutorialHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>iNaturalist Tutorial</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">iNaturalist</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="#">Observations</a></li>
            <li><a href="#about">Species</a></li>
            <li><a href="#contact">People</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    
    <%= yield %>
    
      <hr>

      <footer>
        <p>About iNaturalist</p>
      </footer>

    </div><!-- /.container -->

  </body>
</html>

app/views/tutorial/_sidebar.html.erb
<div class="col-md-3" id="sidebar">
  <div class="list-group">
    <%= link_to "What Is iNaturalist?", root_path, class: 'list-group-item '+active_class(root_path) %>
    <%= link_to "What Are Observations?", observations_path, class: 'list-group-item '+active_class(observations_path) %>
    <%= link_to "What Are Organisms?", organisms_path, class: 'list-group-item '+active_class(organisms_path) %>
    <%= link_to "What Are Identifications?", identifications_path, class: 'list-group-item '+active_class(identifications_path) %>
  </div>
</div><!--/.sidebar-offcanvas-->

app/views/tutorial/identifications.html.erb
    <div class="container">
      <ul class="breadcrumb">
        <li><a href="#">Getting Started</a></li>
        <li class="active">What Are Identifications?</li>
      </ul>
      <div class="row">
        <div class="col-md-9">
          <div class="row">
            <div class="col-md-9" name="what-is-inaturalist">
              <h2>What Are Identifications?</h2>
              <p>iNaturalist helps you record what you see in nature and share with a community of naturalists. Along the way we hope you’ll learn more about what you saw and create research quality data for science.  Here’s how it works...</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
              <embed src="/assets/cullen.svg"></embed>
            </div>
            <div class="col-md-5 col-sm-6 col-xs-12">
              <h2>Observe</h2>
              <p>Cullen sees an interesting snail on a hike in California. He records the encounter as an observation.</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-md-push-5 col-sm-6 col-sm-push-6 col-xs-12">
              <embed src="/assets/susan.svg"></embed>
            </div>
            <div class="col-md-5 col-md-pull-4 col-sm-6 col-sm-pull-6 col-xs-12">
              <h2>Identify</h2>
              <p>Susan is a zoologist in New York. She identifies Cullen’s observation as a Small Pointed Snail. This kind of snail is native to Europe, but is poorly known in California.</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
              <embed src="/assets/michelle.svg"></embed>
            </div>
            <div class="col-md-5 col-sm-6 col-xs-12">
              <h2>Learn</h2>
              <p>Michelle works at the Santa Clara Division of Agriculture. She uses Cullen’s observation in her research to understand and manage this new biological invasion.</p>
            </div>
          </div>
        </div>
        
        <%= render :partial => "sidebar" %>
        
      </div><!--/row-->

app/views/tutorial/inaturalist.html.erb
    <div class="container">
      <ul class="breadcrumb">
        <li><a href="#">Getting Started</a></li>
        <li class="active">What Is iNaturalist?</li>
      </ul>
      <div class="row">
        <div class="col-md-9">
          <div class="row">
            <div class="col-md-9" name="what-is-inaturalist">
              <h2>What is iNaturalist?</h2>
              <p>iNaturalist helps you record what you see in nature and share with a community of naturalists. Along the way we hope you’ll learn more about what you saw and create research quality data for science.  Here’s how it works...</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
              <embed src="/assets/cullen.svg"></embed>
            </div>
            <div class="col-md-5 col-sm-6 col-xs-12">
              <h2>Observe</h2>
              <p>Cullen sees an interesting snail on a hike in California. He records the encounter as an observation.</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-md-push-5 col-sm-6 col-sm-push-6 col-xs-12">
              <embed src="/assets/susan.svg"></embed>
            </div>
            <div class="col-md-5 col-md-pull-4 col-sm-6 col-sm-pull-6 col-xs-12">
              <h2>Identify</h2>
              <p>Susan is a zoologist in New York. She identifies Cullen’s observation as a Small Pointed Snail. This kind of snail is native to Europe, but is poorly known in California.</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
              <embed src="/assets/michelle.svg"></embed>
            </div>
            <div class="col-md-5 col-sm-6 col-xs-12">
              <h2>Learn</h2>
              <p>Michelle works at the Santa Clara Division of Agriculture. She uses Cullen’s observation in her research to understand and manage this new biological invasion.</p>
            </div>
          </div>
        </div>
        
        <%= render :partial => "sidebar" %>
        
      </div><!--/row-->

app/views/tutorial/index.html.erb
    <div class="container">
      <ul class="breadcrumb">
        <li><a href="#">Help</a></li>
        <li class="active">Getting Started</li>
      </ul>
      <div class="row">
        <div class="col-md-9">
          <div class="row">
            <div class="col-md-9" name="what-is-inaturalist">
              <h2>What is iNaturalist?</h2>
              <p>iNaturalist helps you record what you see in nature and share with a community of naturalists. Along the way we hope you’ll learn more about what you saw and create research quality data for science.  Here’s how it works...</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
              <embed src="/assets/cullen.svg"></embed>
            </div>
            <div class="col-md-5 col-sm-6 col-xs-12">
              <h2>Observe</h2>
              <p>Cullen sees an interesting snail on a hike in California. He records the encounter as an observation.</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-md-push-5 col-sm-6 col-sm-push-6 col-xs-12">
              <embed src="/assets/susan.svg"></embed>
            </div>
            <div class="col-md-5 col-md-pull-4 col-sm-6 col-sm-pull-6 col-xs-12">
              <h2>Identify</h2>
              <p>Susan is a zoologist in New York. She identifies Cullen’s observation as a Small Pointed Snail. This kind of snail is native to Europe, but is poorly known in California.</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
              <embed src="/assets/michelle.svg"></embed>
            </div>
            <div class="col-md-5 col-sm-6 col-xs-12">
              <h2>Learn</h2>
              <p>Michelle works at the Santa Clara Division of Agriculture. She uses Cullen’s observation in her research to understand and manage this new biological invasion.</p>
            </div>
          </div>
        </div>
        
        <div class="col-md-3" id="sidebar">
          <div class="list-group">
            <a href="#what-is-inaturalist" class="list-group-item active">What is iNaturalist?</a>
            <a href="#what-are-observations" class="list-group-item">What Are Observations?</a>
            <a href="#what-are-organisms" class="list-group-item">What Are Organisms?</a>
            <a href="#what-are-identifications" class="list-group-item">What Are Identifications?</a>
          </div>
        </div><!--/.sidebar-offcanvas-->
      </div><!--/row-->

app/views/tutorial/observations.html.erb
    <div class="container">
      <ul class="breadcrumb">
        <li><a href="#">Getting Started</a></li>
        <li class="active">What Are Observations?</li>
      </ul>
      <div class="row">
        <div class="col-md-9">
          <div class="row">
            <div class="col-md-9" name="what-is-inaturalist">
              <h2>What Are Observations?</h2>
              <p>iNaturalist helps you record what you see in nature and share with a community of naturalists. Along the way we hope you’ll learn more about what you saw and create research quality data for science.  Here’s how it works...</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
              <embed src="/assets/cullen.svg"></embed>
            </div>
            <div class="col-md-5 col-sm-6 col-xs-12">
              <h2>Observe</h2>
              <p>Cullen sees an interesting snail on a hike in California. He records the encounter as an observation.</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-md-push-5 col-sm-6 col-sm-push-6 col-xs-12">
              <embed src="/assets/susan.svg"></embed>
            </div>
            <div class="col-md-5 col-md-pull-4 col-sm-6 col-sm-pull-6 col-xs-12">
              <h2>Identify</h2>
              <p>Susan is a zoologist in New York. She identifies Cullen’s observation as a Small Pointed Snail. This kind of snail is native to Europe, but is poorly known in California.</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
              <embed src="/assets/michelle.svg"></embed>
            </div>
            <div class="col-md-5 col-sm-6 col-xs-12">
              <h2>Learn</h2>
              <p>Michelle works at the Santa Clara Division of Agriculture. She uses Cullen’s observation in her research to understand and manage this new biological invasion.</p>
            </div>
          </div>
        </div>
        
        <%= render :partial => "sidebar" %>
        
      </div><!--/row-->

app/views/tutorial/organisms.html.erb
    <div class="container">
      <ul class="breadcrumb">
        <li><a href="#">Getting Started</a></li>
        <li class="active">What Are Organisms?</li>
      </ul>
      <div class="row">
        <div class="col-md-9">
          <div class="row">
            <div class="col-md-9" name="what-is-inaturalist">
              <h2>What Are Organisms?</h2>
              <p>iNaturalist helps you record what you see in nature and share with a community of naturalists. Along the way we hope you’ll learn more about what you saw and create research quality data for science.  Here’s how it works...</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
              <embed src="/assets/cullen.svg"></embed>
            </div>
            <div class="col-md-5 col-sm-6 col-xs-12">
              <h2>Observe</h2>
              <p>Cullen sees an interesting snail on a hike in California. He records the encounter as an observation.</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-md-push-5 col-sm-6 col-sm-push-6 col-xs-12">
              <embed src="/assets/susan.svg"></embed>
            </div>
            <div class="col-md-5 col-md-pull-4 col-sm-6 col-sm-pull-6 col-xs-12">
              <h2>Identify</h2>
              <p>Susan is a zoologist in New York. She identifies Cullen’s observation as a Small Pointed Snail. This kind of snail is native to Europe, but is poorly known in California.</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
              <embed src="/assets/michelle.svg"></embed>
            </div>
            <div class="col-md-5 col-sm-6 col-xs-12">
              <h2>Learn</h2>
              <p>Michelle works at the Santa Clara Division of Agriculture. She uses Cullen’s observation in her research to understand and manage this new biological invasion.</p>
            </div>
          </div>
        </div>
        
        <%= render :partial => "sidebar" %>
        
      </div><!--/row-->